### ISSUE TITLE
Toast notification still appearing when joining a server with enforce-secure-profiles = false

### ISSUE THREAD

**Issue by takatalvi** [ocelotpotpie/FreedomChat#50]
Hi, I've just updated my server to 1.20.6 and with it also Freedomchat. I'm happy to say that chat reporting is disabled and also the annoying icons in chat are not visible. But compared to the version used on 1.20.4, this one displays the toast warning when you join a server which does not enforce secure profiles. Is this something that can be fixed, like in previous versions? I'm currently on Paper 1.20.6. build 128. Thanks!

**Comment by pop4959** [comment]
The config option which let you choose to hide it does not exist anymore in 1.20.6 due to technical reasons (see the discussion [here](https://github.com/ocelotpotpie/FreedomChat/commit/33e92244c51545ec913e599882552b9651c7c8f0#comments) for more info).

My understanding is the chat signing support on the server is automatically detected now so you cannot change this without supporting signed chat.

As such, unless some other method of hiding it is found, this will not be fixed.

**Comment by takatalvi** [comment]
Oh, that's unfortunate.. Thanks for the info, though.

**Comment by pop4959** [comment]
Re-labeling as a bug because I have been corrected in that this is still possible.

**Comment by pop4959** [comment]
Latest version now restores this feature - thanks @whiler-sesame!

**Comment by takatalvi** [comment]
Absolutely wonderful, thank you so much for looking into this!
