### ISSUE TITLE
Setting claim-secure-chat-enforced: true to false by default to be MUG compliant

### ISSUE THREAD

**Issue by smashyalts** [ocelotpotpie/FreedomChat#58]
https://github.com/ocelotpotpie/FreedomChat/pull/57 (original PR)
made this issue as asked by pop

**Comment by pop4959** [comment]
I offered you the choice to make an issue so that you could give more context and share your opinion on why this should be changed and get opinions from the community. However, I expect at least minimum effort. This issue, as is, is not worth anyone's time to try to decipher.

If someone is actually interested in this change being made, you are absolutely welcome but please make a proper case and put in at least some effort of making it a discussion.

**Comment by smashyalts** [comment]
i read your previous message as to make a issue where people could talk about it? which is what this issue was meant to do,
the case is that you need it to be set to false to be mug compliant, aka follow the rules of the game, to not get blacklisted that should be enough reason to get it changed at least in my opinion, causes no harm and only makes this plugin not be a reason to get a server mug blacklisted because of a single config option set by default.

**Comment by smashyalts** [comment]
sorry for misunderstanding your question tho, i apologise for that

**Comment by Skullians** [comment]
+1 on this. Several people will not realise that disabling the popup (default) does not comply with the MUG.
By defaulting this to false, server owners will be complying with the MUG and can enable it themselves if the they, for whatever reason, decide not to comply with the MUG.

**Comment by pop4959** [comment]
Re-opening this issue, thanks for adding context. Just keep in mind for the future, opening an issue for discussion without providing any context as to what that discussion is meant to be about, comes across as disingenuous. But anyways...

I am trying to understand, how does changing this option make FreedomChat MUG compliant? My understanding is by disabling chat reporting, you are already not compliant.

Is there evidence to suggest that disabling chat reporting is actually okay per Mojang, and that the toast being disabled is truly the only issue present here?

**Comment by smashyalts** [comment]
![image](https://github.com/user-attachments/assets/da3e6f1f-a449-43a5-9cb8-20778248c2ba)
![image](https://github.com/user-attachments/assets/ace1c828-8aa1-4978-8c22-95db9b379a67)
![image](https://github.com/user-attachments/assets/8c626f26-340e-4021-8cf8-8029b7c68180)
Gamersafer

**Comment by smashyalts** [comment]
![image](https://github.com/user-attachments/assets/4cdaaa7a-cf73-49e1-8a1e-9ba8dc2558c0)
IP_justice (mojang enforcement agent)

**Comment by whiler-sesame** [comment]
I have a few questions and statements for this:
1. What about [NoChatReports](https://github.com/Aizistral-Studios/No-Chat-Reports)? It has an option, enabled by default, that removes these toasts, also contains many other options that hide the functionality of chat reporting.
2. Making it "false" won't make it MUG-complaint. This will change defaults, anyone will still be able to toggle it back. How you see remove the *config option*, not the feature itself will fix this problem?
3. What will be done as a punishment? Will the servers be blocked via Patchy EULA blocking system? Will this repo be DMCAed?
4. What about other mods, plugins, servers, and proxies?
5. What about the core mechanism of this plugin: rewriting PlayerChat packets to SystemChat or DisguisedChat packets. Does it break MUG-compliance? Why yes or why no? Player will see something like "Server chat message. Can't be reported.", but it's not really a server chat message.

**Comment by pop4959** [comment]
@smashyalts Thanks, the screenshot from IP Justice was what I was looking for. That does look compelling in terms of being able to be compliant even with chat reporting disabled. I wish you had shared that initially, as it would have made this a lot more clear-cut.

@whiler-sesame To be the best of my understanding:

1. I don't think we need to compare ourselves to other mods here, but my expectation is they are probably running under the same assumption we have been.
2. IP Justice speaks officially on behalf of Mojang, so if they say that disabling chat reporting is not enforceable, then they are not enforcing it, which implies that the only issue here is modifying the toast. However, giving users the ability to modify the toast itself is *not* a violation, in my understanding. The MUG specifies that this is only for server owners looking to monetize, so it shouldn't be an issue to enable for example, on a private server. However this could probably use clarification.
3. Mojang typically contacts server owners to notify them of violations, and only block servers that fail to respond accordingly.
4. I'm not sure what you mean with this one, but given the variety of mods and plugins out there, it depends on exactly what they're doing.
5. It sounds like it would be, but it's not being enforced currently, which is kind of a silver lining but it does change how we can view things here.
6. That resource pack looks to alter the prompt which seems to me specifically non-compliant with the MUG, but whether or not that would be enforced is another question.

Obviously, FreedomChat does not specifically exist to break compliance with the Minecraft EULA and/or MUG. Most users at this point understand that chat reporting is a good thing, but cannot use it due to technical limitations running servers under a proxy software such as Velocity.

It's evident that IP Justice recognizes this based on their response & position that they are not enforcing this at the moment. At the point where this becomes enforceable, solutions such as FreedomChat would likely no longer be necessary for server owners, provided that improvements have been made to the chat reporting system to properly support it behind the proxy.

**Comment by pop4959** [comment]
Woops, forgot to follow up on this, but aside from the 2 thumbs down (which I'm assuming is in response to the lack of description in the original post), it seems like the general consensus here is that it does make sense to disable by default, which we can do in the next release.

**Comment by smashyalts** [comment]
> Woops, forgot to follow up on this, but aside from the 2 thumbs down (which I'm assuming is in response to the lack of description in the original post), it seems like the general consensus here is that it does make sense to disable by default, which we can do in the next release.

those two downvotes are from my pr/issue in antipopup, one being the creator of antipopup and the other being someone i dont know
Just to clear things up

**Comment by pop4959** [comment]
> > Woops, forgot to follow up on this, but aside from the 2 thumbs down (which I'm assuming is in response to the lack of description in the original post), it seems like the general consensus here is that it does make sense to disable by default, which we can do in the next release.
> 
> those two downvotes are from my pr/issue in antipopup, one being the creator of antipopup and the other being someone i dont know Just to clear things up

Fair enough. Regardless of what, seems like there aren't any comments strongly against, and it's been 2 months.

**Comment by pop4959** [comment]
This issue has been addressed in the latest version of the plugin.

A simple advisory notice has been added as shown below:
![image](https://github.com/user-attachments/assets/96a91131-c404-4bdb-924a-6f9dad1b3296)

That said, I want to remind everyone that regardless of what the default is in FreedomChat, it is every server owner's own responsibility to ensure that their servers are EULA and MUG compliant. Take care in other plugins and settings that you use on your servers as well. While it's a nice gesture for plugins to give a heads-up to protect and inform users of potential compliance concerns, this should not be taken for granted.
